name: Create Backlog Issue with All Parameters

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'  # Daily at midnight

jobs:
  create-basic-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Create a basic Backlog issue
        uses: katayama8000/backlog-github-actions@0.1.0
        with:
          backlog_domain: 'tatsufumi.backlog.com'
          api_key: ${{ secrets.BACKLOG_API_KEY }}
          project_id: '665456'
          issue_type_id: '3529949'
          summary: 'Basic Sample Task'
          priority_id: '3'  # Normal priority

  create-detailed-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Create a detailed Backlog issue with all parameters
        uses: katayama8000/backlog-github-actions@0.1.0
        with:
          backlog_domain: 'tatsufumi.backlog.com'
          api_key: ${{ secrets.BACKLOG_API_KEY }}
          project_id: '665456'
          issue_type_id: '3529949'
          summary: 'Detailed Sample Task with All Parameters'
          priority_id: '2'  # High priority
          description: |
            This is a detailed issue description.
            
            **Tasks to complete:**
            - [ ] Task 1
            - [ ] Task 2
            - [ ] Task 3
            
            Created automatically via GitHub Actions.
          start_date: '2025-09-01'
          due_date: '2025-09-30'
          estimated_hours: '8'
          assignee_id: '123456'  # Replace with actual user ID
          category_ids: '1,2,3'  # Replace with actual category IDs
          version_ids: '10,20'   # Replace with actual version IDs
          milestone_ids: '5'     # Replace with actual milestone ID
          notified_user_ids: '123456,789012'  # Replace with actual user IDs

  create-bug-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Create a bug report issue
        uses: katayama8000/backlog-github-actions@0.1.0
        with:
          backlog_domain: 'tatsufumi.backlog.com'
          api_key: ${{ secrets.BACKLOG_API_KEY }}
          project_id: '665456'
          issue_type_id: '3529950'  # Bug issue type
          summary: 'Bug Report: Auto-generated from CI/CD'
          priority_id: '2'  # High priority
          description: |
            **Bug Description:**
            Automatically detected issue during CI/CD pipeline.
            
            **Environment:**
            - Branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
            - Workflow: ${{ github.workflow }}
            
            **Reproduction Steps:**
            1. Run the pipeline
            2. Check the logs
            3. Verify the error
            
            **Expected Result:**
            Pipeline should complete successfully
            
            **Actual Result:**
            Pipeline failed with errors
          assignee_id: '123456'  # Replace with actual developer ID
          due_date: '2025-09-15'

  create-feature-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Create a feature request
        uses: katayama8000/backlog-github-actions@0.1.0
        with:
          backlog_domain: 'tatsufumi.backlog.com'
          api_key: ${{ secrets.BACKLOG_API_KEY }}
          project_id: '665456'
          issue_type_id: '3529951'  # Feature request issue type
          summary: 'Feature Request: New API Endpoint'
          priority_id: '3'  # Normal priority
          description: |
            **Feature Description:**
            Add a new API endpoint for user management.
            
            **Requirements:**
            - RESTful API design
            - Authentication required
            - Rate limiting
            - Comprehensive documentation
            
            **Acceptance Criteria:**
            - [ ] API endpoint implemented
            - [ ] Unit tests written
            - [ ] Integration tests added
            - [ ] Documentation updated
          start_date: '2025-09-01'
          due_date: '2025-10-31'
          estimated_hours: '40'
          milestone_ids: '5'  # Replace with actual milestone ID
