name: Create Backlog Issue

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Create a new Backlog issue
        uses: katayama8000/backlog-issue-creator@v0.2.0
        with:
          backlog_domain: 'tatsufumi.backlog.com'
          api_key: ${{ secrets.BACKLOG_API_KEY }}
          project_id: '665456'
          issue_type_id: '3529949'
          summary: 'Sample Task'
          priority: 'Normal'
